Repository pallets/werkzeug, pull requests merged in 2019-03, with the labels that each got.

#1470 use sphinx-issues
  CHANGES.rst
  docs/conf.py
  docs/exceptions.rst
  docs/requirements.txt
  setup.py
  tox.ini
Labels: docs

#1472 ignore getuser KeyError for debugger pin
  CHANGES.rst
  src/werkzeug/debug/__init__.py
Labels: debugger

#1494 test client removes cookie header when cookie jar is empty
  CHANGES.rst
  src/werkzeug/test.py
  tests/test_test.py
Labels: bug

#1496 Don't ignore Set-Cookie directives when parsing Cookie header
  CHANGES.rst
  src/werkzeug/_internal.py
  tests/test_http.py
Labels: bug
