Repository pallets/werkzeug, pull requests merged in 2021-08, with the labels that each got.

#2170 Fix type hints for TypeConversionDict.get
  CHANGES.rst
  src/werkzeug/datastructures.pyi
Labels: typing

#2185 Fix type annotations of RuleFactory classes
  CHANGES.rst
  src/werkzeug/routing.py
Labels: typing

#2199 Fix missing __getattr__ in FileStorage's interface
  CHANGES.rst
  src/werkzeug/datastructures.pyi
Labels: typing

#2207 debugger cookie uses SameSite=Strict
  CHANGES.rst
  src/werkzeug/debug/__init__.py
Labels: debugger

#2208 document server shutdown without deprecated dev function
  docs/serving.rst
Labels: docs

#2209 use IO[bytes] instead of BinaryIO for wider compatibility
  CHANGES.rst
  src/werkzeug/datastructures.pyi
  src/werkzeug/debug/tbtools.py
  src/werkzeug/formparser.py
  src/werkzeug/middleware/lint.py
  src/werkzeug/middleware/profiler.py
  src/werkzeug/middleware/shared_data.py
  src/werkzeug/serving.py
  src/werkzeug/test.py
  src/werkzeug/urls.py
  src/werkzeug/utils.py
  src/werkzeug/wrappers/request.py
  src/werkzeug/wsgi.py
Labels: typing

#2210 Update mypy
  requirements/dev.txt
  requirements/docs.txt
  requirements/tests.txt
  requirements/typing.in
  requirements/typing.txt
  src/werkzeug/datastructures.pyi
Labels: typing

#2214 update pip link
  README.rst
Labels: docs
