Repository pallets/werkzeug, pull requests merged in 2021-01, with the labels that each got.

#1989 Add end of word character for OR regex raw strings in platforms list
  CHANGES.rst
  src/werkzeug/useragents.py
  tests/test_useragents.py
Labels: user-agent

#2001 document that single quote is escaped
  src/werkzeug/utils.py
Labels: docs

#2005 SansIO Wrappers
  CHANGES.rst
  src/werkzeug/http.py
  src/werkzeug/sansio/__init__.py
  src/werkzeug/sansio/request.py
  src/werkzeug/sansio/response.py
  src/werkzeug/urls.py
  src/werkzeug/wrappers/request.py
  src/werkzeug/wrappers/response.py
  tests/test_wrappers.py
Labels: ASGI
