Repository pallets/werkzeug, pull requests merged in 2022-01, with the labels that each got.

#2321 show instructions for "address already in use" error, and other dev server improvements
  requirements/dev.txt
  requirements/tests.in
  requirements/tests.txt
  setup.cfg
  src/werkzeug/serving.py
  tests/conftest.py
Labels: server

#2322 optimize stat reloader
  CHANGES.rst
  src/werkzeug/_reloader.py
  tests/live_apps/reloader_app.py
Labels: reloader

#2091 use chunked encoding for streaming responses with HTTP/1.1
  CHANGES.rst
  src/werkzeug/serving.py
  tests/live_apps/run.py
  tests/live_apps/streaming_app.py
  tests/test_serving.py
Labels: server

#2323 more HTTP/1.1 fixes
  CHANGES.rst
  src/werkzeug/debug/__init__.py
  src/werkzeug/serving.py
  tests/live_apps/run.py
  tests/test_serving.py
Labels: server, debugger
